### ISSUE TITLE
Successfully/unsuccessfully adding/removing group members appears the same

### ISSUE THREAD

**Issue by mjtko** [alces-software/userware#29]
Successful addition to a group:

```
directory> group add-member coolpeople thisguy
directory>
```

Unsuccessful addition to a group (i.e. no user specified):

```
directory> group add-member coolpeople
directory>
```

I'd expect the latter to generate an error message.  And, ideally, the former to generate a success message! :)

Similar things happen for `remove-member`, and also `hostgroup add-member` and `hostgroup remove-member`.

**Comment by DavidMarchant** [comment]
Just to say, for future reference, the function I created to generate informative error messages for the add/remove-member commands is fairly computationally intensive/inefficient & should likely be disabled if speed becomes an issue when managing groups
