### ISSUE TITLE
Host blacklist not working properly

### ISSUE THREAD

**Issue by DavidMarchant** [alces-software/userware#31]
Due to some host commands allowing just a host's name and others necessitating a fully qualified domain the blacklist isn't fully blocking everything it should. 
I think best idea is possibly to block all blacklisted hosts both with and without their domains?

Message me if you want a full list of the commands interactions

**Comment by DavidMarchant** [comment]
worth mentioning actually that it's only our side that's failing for the most part. IPA stops deletion or creation of the blacklist hosts, it does allow modification however

**Comment by mjtko** [comment]
Yup, sounds good. Block with and without domains.
