### ISSUE TITLE
Add some form of pagination to the output of the list commands 

### ISSUE THREAD

**Issue by DavidMarchant** [alces-software/userware#39]
As it stands when a `list` command is used & produces a large number of results the output is fairly unworkable, some form of formatting/segmentation of the table is needed

**Comment by bobwhitelock** [comment]
Couple of pointers for doing this:

- If we just want to always paginate for `list` commands, it should hopefully be as simple as replacing the call to `click.echo` within these with a call to [`click.echo_via_pager`](http://click.pocoo.org/5/utils/#pager-support).

- If we want to only paginate if there's more than one page of output, we may need to invoke `less` ourselves - look into the `less --quit-if-one-screen` flag.

**Comment by DavidMarchant** [comment]
Ah! Thanks a lot Bob, I'll look into those
