### ISSUE TITLE
User creation default settings config file

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/userware#66]
It would be useful to have a simple config file that can be changed on an install by install basis that could be used to set things like:
- GID number
- Toggle random/no-password

**Comment by ColonelPanicks** [comment]
To clarify further (thanks to @mjtko input)
1. Have a config file for user creation
2. Config file contains fields: “default gid” (i.e. gid to use if not specified), “password_policy” (i.e. random/none) and “post_create_script”
3. If “post_create_script” is configured, run it post-creation

**Comment by mjtko** [comment]
`post_create_script` should be provided with the username

**Comment by DavidMarchant** [comment]
Hey, I am assuming we are wanting to support cases in which a customer hasn't set all of the possible config fields?

**Comment by DavidMarchant** [comment]
ok, yep, working for both eventualities
