### ISSUE TITLE
Add SSH public key option as separate command 

### ISSUE THREAD

**Issue by ste78** [alces-software/userware#85]
Allow in non-advanced mode addition of multiple SSH pub keys and be able to show what ones are set etc

**Comment by ste78** [comment]
need u to flesh this out plz stewie, grab me

**Comment by ColonelPanicks** [comment]
IPA allows for the addition of SSH access keys to existing users. What we're looking for is:

- SSH key management command
    - Add SSH key to user (`ipa user-mod USERNAME --sshpubkey="ssh-rsa 123456778113857468429353575486 user@host"`)
    - Remove SSH keys for user (`ipa user-mod USERNAME --sshpubkey=`)
- CLI flag for user creation to specify an SSH key (this should be optional and not available in the prompt) (`--sshpubkey`)
